=== Pocketsnb/Random-Generator/RandomGenerator/Schema/MagicItemsSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    id="MagicItemsSchema">

  <xs:complexType name="TextProbType">
    <xs:attribute name="Text" type="xs:string" />
    <xs:attribute name="Probability" type="xs:int" />
  </xs:complexType>

  <xs:complexType name="StandardType">
    <xs:sequence>
      <xs:element name="Value" maxOccurs="unbounded" type="TextProbType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="MagicItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TableA" type="StandardType" />
        <xs:element name="TableB" type="StandardType" />
        <xs:element name="TableC" type="StandardType" />
        <xs:element name="TableD" type="StandardType" />
        <xs:element name="TableE" type="StandardType" />
        <xs:element name="TableF" type="StandardType" />
        <xs:element name="TableG" type="StandardType" />
        <xs:element name="TableH" type="StandardType" />
        <xs:element name="TableI" type="StandardType" />
        <xs:element name="Figurine" type="StandardType" />
        <xs:element name="MagicArmor" type="StandardType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Pocketsnb/Random-Generator/RandomGenerator/XML/MagicItems.xml
<?xml version="1.0" encoding="utf-8"?>
<MagicItems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../Schema/MagicItemsSchema.xsd">
  <!--From DMG 5e pg 144 Random Magic Items-->
  <TableA>
    <Value Text="Potion of healing" Probability="50" />
    <Value Text="Spell scroll (cantrip)" Probability="10" />
    <Value Text="Potion of climbing" Probability="10" />
    <Value Text="Spell scroll (1st level)" Probability="20" />
    <Value Text="Spell scroll (2nd level)" Probability="4" />
    <Value Text="Potion of greater healing" Probability="4" />
    <Value Text="Bag of holding" Probability="1" />
    <Value Text="Driftglobe" Probability="1" />
  </TableA>
  <TableB>
    <Value Text="Potion of greater healing" Probability="15" />
    <Value Text="Potion of fire breath" Probability="7" />
    <Value Text="Potion of resistance" Probability="7" />
    <Value Text="Ammunition, +1" Probability="5" />
    <Value Text="Potion of animal friendship" Probability="5" />
    <Value Text="Potion of hill giant strength" Probability="5" />
    <Value Text="Potion of growth" Probability="5" />
    <Value Text="Potion of water breathing" Probability="5" />
    <Value Text="Spell scroll (2nd level)" Probability="5" />
    <Value Text="Spell scroll (3rd level)" Probability="5" />
    <Value Text="Bag of holding" Probability="3" />
    <Value Text="Keoghtom's ointment" Probability="3" />
    <Value Text="Oil of slipperiness" Probability="3" />
    <Value Text="Dust of disappearance" Probability="2" />
    <Value Text="Dust of dryness" Probability="2" />
    <Value Text="Dust of sneezing and choking" Probability="2" />
    <Value Text="Elemental gem" Probability="2" />
    <Value Text="Philter of love" Probability="2" />
    <Value Text="Alchemy jug" Probability="1" />
    <Value Text="Cap of water breathing" Probability="1" />
    <Value Text="Cloak of the manta ray" Probability="1" />
    <Value Text="Driftglobe" Probability="1" />
    <Value Text="Goggles of night" Probability="1" />
    <Value Text="Helm of comprehending languages" Probability="1" />
    <Value Text="Immovable rod" Probability="1" />
    <Value Text="Lantern of revealing" Probability="1" />
    <Value Text="Mariner's armor" Probability="1" />
    <Value Text="Mithral armor" Probability="1" />
    <Value Text="Potion of poison" Probability="1" />
    <Value Text="Ring of swimming" Probability="1" />
    <Value Text="Robe of useful items" Probability="1" />
    <Value Text="Rope of climbing" Probability="1" />
    <Value Text="Saddle of the cavalier" Probability="1" />
    <Value Text="Wand of magic detection" Probability="1" />
    <Value Text="Wand of secrets" Probability="1" />
  </TableB>
  <TableC>
    <Value Text="Potion of superior healing" Probability="15" />
    <Value Text="Spell scroll (4th level)" Probability="7" />
    <Value Text="Ammunition, +2" Probability="5" />
    <Value Text="Potion of clairvoyance" Probability="5" />
    <Value Text="Potion of diminution" Probability="5" />
    <Value Text="Potion of gaseous form" Probability="5" />
    <Value Text="Potion of frost giant strength" Probability="5" />
    <Value Text="Potion of stone giant strength" Probability="5" />
    <Value Text="Potion of heroism" Probability="5" />
    <Value Text="Potion of invulnerability" Probability="5" />
    <Value Text="Potion of mind reading" Probability="5" />
    <Value Text="Spell scroll (5th le vel)" Probability="5" />
    <Value Text="Elixir of health" Probability="3" />
    <Value Text="Oil of etherealness" Probability="3" />
    <Value Text="Potion of fire giant strength" Probability="3" />
    <Value Text="Quaal's feather token" Probability="3" />
    <Value Text="Scroll of protection" Probability="3" />
    <Value Text="Bag of beans" Probability="2" />
    <Value Text="Bead of force" Probability="2" />
    <Value Text="Chime of opening" Probability="1" />
    <Value Text="Decanter of endless water" Probability="1" />
    <Value Text="Eyes of minute seeing" Probability="1" />
    <Value Text="Folding boat" Probability="1" />
    <Value Text="Heward's handy haversack" Probability="1" />
    <Value Text="Horseshoes of speed" Probability="1" />
    <Value Text="Necklace of fireballs" Probability="1" />
    <Value Text="Periapt of health" Probability="1" />
    <Value Text="Sending stones" Probability="1" />
  </TableC>
  <TableD>
    <Value Text="Potion of supreme healing" Probability="20" />
    <Value Text="Potion of invisibility" Probability="10" />
    <Value Text="Potion of speed" Probability="10" />
    <Value Text="Spell scroll (6th level)" Probability="10" />
    <Value Text="Spell scroll (7th level)" Probability="7" />
    <Value Text="Ammunition, +3" Probability="5" />
    <Value Text="Oil of sharpness" Probability="5" />
    <Value Text="Potion of flying" Probability="5" />
    <Value Text="Potion of cloud giant strength" Probability="5" />
    <Value Text="Potion of longevity" Probability="5" />
    <Value Text="Potion of vitality" Probability="5" />
    <Value Text="Spell scroll (8th level)" Probability="5" />
    <Value Text="Horseshoes of a zephyr" Probability="3" />
    <Value Text="Nolzur's marvelous pigments" Probability="3" />
    <Value Text="Bag of devouring" Probability="1" />
    <Value Text="Portable hole" Probability="1" />
  </TableD>
  <TableE>
    <Value Text="Spell scroll (8th level)" Probability="30" />
    <Value Text="Potion of storm giant strength" Probability="25" />
    <Value Text="Potion of supreme healing" Probability="15" />
    <Value Text="Spell scroll (9th level)" Probability="15" />
    <Value Text="Universal solvent" Probability="8" />
    <Value Text="Arrow of slaying" Probability="5" />
    <Value Text="Sovereign glue" Probability="2" />
  </TableE>
  <TableF>
    <Value Text="Weapon, +1" Probability="15" />
    <Value Text="Shield,+ 1" Probability="3" />
    <Value Text="Sentinel shield" Probability="3" />
    <Value Text="Amulet of proof against detection and location" Probability="2" />
    <Value Text="Boots of elvenkind" Probability="2" />
    <Value Text="Boots of striding and springing" Probability="2" />
    <Value Text="Bracers of archery" Probability="2" />
    <Value Text="Brooch of shielding" Probability="2" />
    <Value Text="Broom of flying" Probability="2" />
    <Value Text="Cloak of elvenkind" Probability="2" />
    <Value Text="Cloak of protection" Probability="2" />
    <Value Text="Gauntlets of ogre power" Probability="2" />
    <Value Text="Hat of disguise" Probability="2" />
    <Value Text="Javelin of lightning" Probability="2" />
    <Value Text="Pearl of power" Probability="2" />
    <Value Text="Rod of the pact keeper, + 1" Probability="2" />
    <Value Text="Slippers of spider climbing" Probability="2" />
    <Value Text="Staff of the adder" Probability="2" />
    <Value Text="Staff of the python" Probability="2" />
    <Value Text="Sword of vengeance" Probability="2" />
    <Value Text="Trident of fish command" Probability="2" />
    <Value Text="Wand of magic missiles" Probability="2" />
    <Value Text="Wand of the war mage, + 1" Probability="2" />
    <Value Text="Wand of web" Probability="2" />
    <Value Text="Weapon of warning" Probability="2" />
    <Value Text="Adamantine armor (chain mail)" Probability="1" />
    <Value Text="Adamantine armor (chain shirt)" Probability="1" />
    <Value Text="Adamantine armor (scale mail)" Probability="1" />
    <Value Text="Bag of tricks (gray)" Probability="1" />
    <Value Text="Bag of tricks (rust)" Probability="1" />
    <Value Text="Bag of tricks (tan)" Probability="1" />
    <Value Text="Boots of the winterlands" Probability="1" />
    <Value Text="Circlet of blasting" Probability="1" />
    <Value Text="Deck of illusions" Probability="1" />
    <Value Text="Eversmoking bottle" Probability="1" />
    <Value Text="Eyes of charming" Probability="1" />
    <Value Text="Eyes of the eagle" Probability="1" />
    <Value Text="Figurine of wondrous power (silver raven)" Probability="1" />
    <Value Text="Gem of brightness" Probability="1" />
    <Value Text="Gloves of missile snaring" Probability="1" />
    <Value Text="Gloves of swimming and climbing" Probability="1" />
    <Value Text="Gloves of thievery" Probability="1" />
    <Value Text="Headband of intellect" Probability="1" />
    <Value Text="Helm of telepathy" Probability="1" />
    <Value Text="Instrument of the bards (Doss lute)" Probability="1" />
    <Value Text="Instrument of the bards (Fochlucan bandore)" Probability="1" />
    <Value Text="Instrument of the bards (Mac-Fuimidh cittern)" Probability="1" />
    <Value Text="Medallion of thoughts" Probability="1" />
    <Value Text="Necklace of adaptation" Probability="1" />
    <Value Text="Periapt of wound closure" Probability="1" />
    <Value Text="Pipes of haunting" Probability="1" />
    <Value Text="Pipes of the sewers" Probability="1" />
    <Value Text="Ring of jumping" Probability="1" />
    <Value Text="Ring of mind shielding" Probability="1" />
    <Value Text="Ring of warmth" Probability="1" />
    <Value Text="Ring of water walking" Probability="1" />
    <Value Text="Quiver of Ehlonna" Probability="1" />
    <Value Text="Stone of good luck" Probability="1" />
    <Value Text="Wind fan" Probability="1" />
    <Value Text="Winged boots" Probability="1" />
  </TableF>
  <TableG>
    <Value Text="Weapon, +2" Probability="11" />
    <Value Text="Figurine of wonderus power (roll d8)" Probability="3" />
    <Value Text="Adamantine armor (breastplate)" Probability="1" />
    <Value Text="Adamantine armor (splint)" Probability="1" />
    <Value Text="Amulet of health" Probability="1" />
    <Value Text="Armor of vulnerability" Probability="1" />
    <Value Text="Arrow-catching shield" Probability="1" />
    <Value Text="Belt of dwarvenkind" Probability="1" />
    <Value Text="Belt of hill giant strength" Probability="1" />
    <Value Text="Berserker axe" Probability="1" />
