=== Pocketsnb/Random-Generator/RandomGenerator/Schema/TreasuresSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    id="TreasuresSchema">

  <xs:complexType name="TextProbType">
    <xs:attribute name="Text" type="xs:string" />
    <xs:attribute name="Probability" type="xs:int" />
  </xs:complexType>

  <xs:complexType name="StandardType">
    <xs:sequence>
      <xs:element name="Value" maxOccurs="unbounded" type="TextProbType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DescriptionType">
    <xs:sequence>
      <xs:element name="Value" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Description" type="xs:string"/>
          </xs:sequence>
          <xs:attribute name="Text" type="xs:string" />
          <xs:attribute name="Probability" type="xs:int" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DiceType">
    <xs:attribute name="DieCount" type="xs:int" />
    <xs:attribute name="DieType" type="xs:int" />
    <xs:attribute name="DieMultiplier" type="xs:int" />
  </xs:complexType>

  <xs:complexType name="DescriptiveDiceType">
    <xs:attribute name="ObjectType" type="xs:string" />
    <xs:attribute name="DieCount" type="xs:int" />
    <xs:attribute name="DieType" type="xs:int" />
    <xs:attribute name="DieMultiplier" type="xs:int" />
  </xs:complexType>

  <xs:complexType name="CoinCollectionType">
    <xs:sequence>
      <xs:element name="CP" type="DiceType"/>
      <xs:element name="SP" type="DiceType"/>
      <xs:element name="EP" type="DiceType"/>
      <xs:element name="GP" type="DiceType"/>
      <xs:element name="PP" type="DiceType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ObjectsType">
    <xs:sequence>
      <xs:element name="Gems" type="DescriptiveDiceType"/>
      <xs:element name="Art" type="DescriptiveDiceType"/>
      <xs:element name="Magic" maxOccurs="unbounded" type="DescriptiveDiceType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="IndividualType">
    <xs:sequence>
      <xs:element name="Value" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Coins" type="CoinCollectionType" />
          </xs:sequence>
          <xs:attribute name="Text" type="xs:string" />
          <xs:attribute name="Probability" type="xs:int" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="HordeType">
    <xs:sequence>
      <xs:element name="Coins" type="CoinCollectionType" />
      <xs:element name="Value" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Objects" type="ObjectsType" />
          </xs:sequence>
          <xs:attribute name="Text" type="xs:string" />
          <xs:attribute name="Probability" type="xs:int" />
        </xs:complexType>
      </xs:element>

    </xs:sequence>
  </xs:complexType>

  <xs:element name="Treasures">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Gemstones10gp" type="DescriptionType" />
        <xs:element name="Gemstones50gp" type="DescriptionType" />
        <xs:element name="Gemstones100gp" type="DescriptionType" />
        <xs:element name="Gemstones500gp" type="DescriptionType" />
        <xs:element name="Gemstones1000gp" type="DescriptionType" />
        <xs:element name="Gemstones5000gp" type="DescriptionType" />
        <xs:element name="ArtObjects25gp" type="StandardType" />
        <xs:element name="ArtObjects250gp" type="StandardType" />
        <xs:element name="ArtObjects750gp" type="StandardType" />
        <xs:element name="ArtObjects2500gp" type="StandardType" />
        <xs:element name="ArtObjects7500gp" type="StandardType" />
        <xs:element name="IndividualTreasure0-4" type="IndividualType" />
        <xs:element name="IndividualTreasure5-10" type="IndividualType" />
        <xs:element name="IndividualTreasure11-16" type="IndividualType" />
        <xs:element name="IndividualTreasure17" type="IndividualType" />
        <xs:element name="HoardTreasure0-4" type="HordeType" />
        <xs:element name="HoardTreasure5-10" type="HordeType" />
        <xs:element name="HoardTreasure11-16" type="HordeType" />
        <xs:element name="HoardTreasure17" type="HordeType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Pocketsnb/Random-Generator/RandomGenerator/XML/Treasures.xml
<?xml version="1.0" encoding="utf-8"?>
<Treasures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="../Schema/TreasuresSchema.xsd">
  <!--From DMG 5e pg 133 Treasure Tables -->
  <Gemstones10gp>
    <Value Text="Azurite" Probability="1">
      <Description>opaque mottled deep blue</Description>
    </Value>
    <Value Text="Banded agate (" Probability="1">
      <Description>translucent striped brown, blue, white, or red</Description>
    </Value>
    <Value Text="Blue quartz" Probability="1">
      <Description>transparent pale blue</Description>
    </Value>
    <Value Text="Eye agate" Probability="1">
      <Description>translucent circles of gray, white, brown, blue, or green</Description>
    </Value>
    <Value Text="Hematite" Probability="1">
      <Description>opaque gray-black</Description>
    </Value>
    <Value Text="Lapis lazuli" Probability="1">
      <Description>opaque light and dark blue with yellow flecks</Description>
    </Value>
    <Value Text="Malachite" Probability="1">
      <Description>opaque striated light and dark green</Description>
    </Value>
    <Value Text="Moss agate (" Probability="1">
      <Description>translucent pink or yellow-white with mossy gray or green markings</Description>
    </Value>
    <Value Text="Obsidian" Probability="1">
      <Description>opaque black</Description>
    </Value>
    <Value Text="Rhodochrosite" Probability="1">
      <Description>opaque light pink</Description>
    </Value>
    <Value Text="Tiger eye" Probability="1">
      <Description>translucent brown with golden center</Description>
    </Value>
    <Value Text="Turquoise" Probability="1">
      <Description>opaque light blue-green</Description>
    </Value>
  </Gemstones10gp>
  <Gemstones50gp>
    <Value Text="Bloodstone" Probability="1">
      <Description>opaque dark gray with red flecks</Description>
    </Value>
    <Value Text="Carnelian" Probability="1">
      <Description>opaque orange to red-brown</Description>
    </Value>
    <Value Text="Chalcedony" Probability="1">
      <Description>opaque white</Description>
    </Value>
    <Value Text="Chrysoprase" Probability="1">
      <Description>translucent green</Description>
    </Value>
    <Value Text="Citrine" Probability="1">
      <Description>transparent pale yellow-brown</Description>
    </Value>
    <Value Text="Jasper" Probability="1">
      <Description>opaque blue, black, or brown</Description>
    </Value>
    <Value Text="Moonstone" Probability="1">
      <Description>translucent white with pale blue glow</Description>
    </Value>
    <Value Text="Onyx" Probability="1">
      <Description>opaque bands of black and white, or pure black or white</Description>
    </Value>
    <Value Text="Quartz" Probability="1">
      <Description>transparent white, smoky gray, or yellow</Description>
    </Value>
    <Value Text="Sardonyx" Probability="1">
      <Description>opaque bands of red and white</Description>
    </Value>
    <Value Text="Star rose quartz" Probability="1">
      <Description>translucent rosy stone with white star-shaped center</Description>
    </Value>
    <Value Text="Zircon" Probability="1">
      <Description>transparent pale blue-green</Description>
    </Value>
  </Gemstones50gp>
  <Gemstones100gp>
    <Value Text="Amber" Probability="1">
      <Description>transparent watery gold to rich gold</Description>
    </Value>
    <Value Text="Amethyst" Probability="1">
      <Description>transparent deep purple</Description>
    </Value>
    <Value Text="Chrysoberyl" Probability="1">
      <Description>transparent yellow-green to pale green</Description>
    </Value>
    <Value Text="Coral" Probability="1">
      <Description>opaque crimson</Description>
    </Value>
    <Value Text="Garnet" Probability="1">
      <Description>transparent red, brown-green, or violet</Description>
    </Value>
    <Value Text="jade" Probability="1">
      <Description>translucent light green, deep green, or white</Description>
    </Value>
    <Value Text="jet" Probability="1">
      <Description>opaque deep black</Description>
    </Value>
    <Value Text="Pearl" Probability="1">
      <Description>opaque lustrous white, yellow, or pink</Description>
    </Value>
    <Value Text="Spinel" Probability="1">
      <Description>transparent red, red-brown, or deep green</Description>
    </Value>
    <Value Text="Tourmaline" Probability="1">
      <Description>transparent pale green , blue, brown, or red</Description>
    </Value>
  </Gemstones100gp>
  <Gemstones500gp>
    <Value Text="Alexandrite" Probability="1">
      <Description>transparent dark green</Description>
    </Value>
    <Value Text="Aquamarine" Probability="1">
      <Description>transparent pale blue-green</Description>
    </Value>
    <Value Text="Black pearl" Probability="1">
      <Description>opaque pure black</Description>
    </Value>
    <Value Text="Blue spinel" Probability="1">
      <Description>transparent deep blue</Description>
    </Value>
    <Value Text="Peridot" Probability="1">
      <Description>transparent rich olive green</Description>
    </Value>
    <Value Text="Topaz" Probability="1">
      <Description>transparent golden yellow</Description>
    </Value>
  </Gemstones500gp>
  <Gemstones1000gp>
    <Value Text="Black opal" Probability="1">
      <Description>translucent dark green with black mottling and golden flecks</Description>
    </Value>
    <Value Text="Blue sapphire" Probability="1">
      <Description>transparent blue-white to medium blue</Description>
    </Value>
    <Value Text="Emerald" Probability="1">
      <Description>transparent deep bright green</Description>
    </Value>
    <Value Text="Fire opal" Probability="1">
      <Description>translucent fiery red</Description>
    </Value>
    <Value Text="Opal" Probability="1">
      <Description>translucent pale blue with green and golden mottling</Description>
    </Value>
    <Value Text="Star ruby" Probability="1">
      <Description>translucent ruby with white star-shaped center</Description>
    </Value>
    <Value Text="Star sapphire" Probability="1">
      <Description>translucent blue sapphire with white star-shaped center</Description>
    </Value>
    <Value Text="Yellow sapphire" Probability="1">
      <Description>transparent fiery yellow or yellow-green</Description>
    </Value>
  </Gemstones1000gp>
  <Gemstones5000gp>
    <Value Text="Black sapphire" Probability="1">
      <Description>translucent lustrous black with glowing highlights</Description>
    </Value>
    <Value Text="Diamond" Probability="1">
      <Description>transparent blue-white, canary, pink, brown, or blue</Description>
    </Value>
    <Value Text="Jacinth" Probability="1">
      <Description>transparent fiery orange</Description>
    </Value>
    <Value Text="Ruby" Probability="1">
      <Description>transparent clear red to deep crimson</Description>
    </Value>
  </Gemstones5000gp>
  <ArtObjects25gp>
    <Value Text="Silver ewer" Probability="1" />
    <Value Text="Carved bone statuette" Probability="1" />
    <Value Text="Small gold bracelet" Probability="1" />
    <Value Text="Cloth-of-gold vestments" Probability="1" />
    <Value Text="Black velvet mask stitched with silver thread" Probability="1" />
    <Value Text="Copper chalice with silver filigree" Probability="1" />
    <Value Text="Pair of engraved bone dice" Probability="1" />
    <Value Text="Small mirror set in a painted wooden frame" Probability="1" />
    <Value Text="Embroidered silk handkerchief" Probability="1" />
    <Value Text="Gold locket with a painted portrait inside" Probability="1" />
  </ArtObjects25gp>
  <ArtObjects250gp>
    <Value Text="Gold ring set with bloodstones" Probability="1" />
    <Value Text="Carved ivory statuette" Probability="1" />
    <Value Text="Large gold bracelet" Probability="1" />
    <Value Text="Silver necklace with a gemstone pendant" Probability="1" />
    <Value Text="Bronze crown" Probability="1" />
    <Value Text="Silk robe with gold embroidery" Probability="1" />
    <Value Text="Large well-made tapestry" Probability="1" />
    <Value Text="Bra ss mug with jade inlay" Probability="1" />
    <Value Text="Box of turquoise animal figurines" Probability="1" />
    <Value Text="Gold bird cage with electrum filigree" Probability="1" />
  </ArtObjects250gp>
  <ArtObjects750gp>
    <Value Text="Silver chalice set with moonstones" Probability="1" />
    <Value Text="Silver-plated steellongsword with jet set in hilt" Probability="1" />
    <Value Text="Carved harp of exotic wood with ivory inlay and zircon gems" Probability="1" />
    <Value Text="Small gold idol" Probability="1" />
    <Value Text="Gold dragon comb set with red garnets as eyes" Probability="1" />
    <Value Text="Bottle stopper cork embossed with gold leaf and set with amethysts" Probability="1" />
    <Value Text="Ceremonial electrum dagger wit~ a black pearl in the pommel" Probability="1" />
    <Value Text="Silver and gold brooch" Probability="1" />
    <Value Text="Obsidian statuette with gold fittings and inlay" Probability="1" />
    <Value Text="Painted gold war mask" Probability="1" />
  </ArtObjects750gp>
  <ArtObjects2500gp>
    <Value Text="Fine gold chain set with a fire opal" Probability="1" />
    <Value Text="Old masterpiece painting" Probability="1" />
    <Value Text="Embroidered silk and velvet mantle set with numerous moonstones" Probability="1" />
    <Value Text="Platinum bracelet set with a sapphire" Probability="1" />
    <Value Text="Embroidered glove set with jewel chips" Probability="1" />
    <Value Text="Jeweled anklet" Probability="1" />
    <Value Text="Gold music box" Probability="1" />
    <Value Text="Gold circlet set with four aquamarines" Probability="1" />
    <Value Text="Eye patch with a mock eye set in blue sapphire and moonstone" Probability="1" />
    <Value Text="A necklace string of small pink pearls" Probability="1" />
